name: Code Review
on: [pull_request]
jobs:
  golangci-lint:
    name: Code Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: go build api
        working-directory: goapp
      - name: Test
        run: go test
        working-directory: goapp
      - name: Analytics
        uses: ducla5/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          golangci_lint_flags: "--disable-all --exclude-use-default=false -E deadcode -E errcheck -E unused -E gofmt -E goimports -E golint -E gocritic -E whitespace"
          directory: goapp/
          reporter: github-pr-check
          tool_name: CodeReview 
