name: Code Review
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: ducla5/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          golangci_lint_flags: "--enable-all --exclude-use-default=false"
          directory: goapp/
          reporter: github-pr-review 
